### ISSUE TITLE
[Suggestion] Bring in sprintf.js as a dependency

### ISSUE THREAD

**Issue by perrin4869** [i18next/i18next-sprintf-postProcessor#2]
I was wondering if it might be a good idea to bring in [sprintf.js](https://github.com/alexei/sprintf.js) as a dependency, instead of providing your own implementation of `sprintf`. Totally willing to send a pull request if you'd like.

**Comment by jamuhl** [comment]
nope...won't add that again...just adds extra weight for the ones not using it.

**Comment by jamuhl** [comment]
there is sprintf postprocessor for that want to have an alternative to the built in interpolation.

**Comment by perrin4869** [comment]
got it!
